// Homepage: renders the CV sidebar and the work grid.
// Data sources:
//   data/cv.json          — hand-maintained CV (sections, items, links, display mode)
//   projects/index.json   — generated by build-projects.mjs from projects/<slug>/<slug>.md
//
// A CV item appears in the grid when it is either a built case study
// (display: "case-study" with a matching projects/ entry) or a direct
// external link (display: "external"). Everything appears in the sidebar.

const state = {
  cv: null,
  projects: [],
  query: '',
  activeTags: new Set(),
};

const EXT_LABELS = {
  'google-photos': 'PHOTOS ↗',
  vimeo: 'VIMEO ↗',
  youtube: 'YOUTUBE ↗',
  soundcloud: 'SOUNDCLOUD ↗',
  bandcamp: 'BANDCAMP ↗',
  instagram: 'INSTAGRAM ↗',
  medium: 'MEDIUM ↗',
  website: 'VISIT ↗',
};

async function fetchJson(url, fallback) {
  try {
    const res = await fetch(`${url}?t=${Date.now()}`);
    if (!res.ok) return fallback;
    return await res.json();
  } catch {
    return fallback;
  }
}

function cvItems() {
  return state.cv.sections.flatMap(s => s.items.map(i => ({ ...i, section: s.title })));
}

// ---------- grid ----------

function gridEntries() {
  const bySlug = new Map(state.projects.map(p => [p.id, p]));
  const entries = [];

  for (const item of cvItems()) {
    const project = bySlug.get(item.slug);
    if (project) {
      entries.push({
        kind: 'case-study',
        href: `projects/${project.id}/`,
        title: project.title || item.title,
        client: project.client || '',
        date: project.date || `${item.year}`,
        year: item.year,
        desc: project.description || item.blurb,
        thumb: projectThumb(project) || thumbFor(item),
        tags: project.hashtags?.length ? project.hashtags : item.tags || [],
      });
    } else if (item.display === 'external' && item.link) {
      entries.push({
        kind: 'external',
        href: item.link,
        badge: EXT_LABELS[item.linkType] || 'VISIT ↗',
        title: item.title,
        client: '',
        date: `${item.year}`,
        year: item.year,
        desc: item.blurb,
        thumb: thumbFor(item),
        tags: item.tags || [],
      });
    }
  }

  // any generated project not present in the CV still gets a card
  const cvSlugs = new Set(cvItems().map(i => i.slug));
  for (const p of state.projects) {
    if (!cvSlugs.has(p.id)) {
      entries.push({
        kind: 'case-study',
        href: `projects/${p.id}/`,
        title: p.title,
        client: p.client || '',
        date: p.date || '',
        year: parseInt(p.date, 10) || 0,
        desc: p.description || '',
        thumb: projectThumb(p),
        tags: p.hashtags || [],
      });
    }
  }

  return entries.sort((a, b) => (b.date || '').localeCompare(a.date || ''));
}

function thumbFor(item) {
  return item.thumb || `assets/thumbs/${item.slug}.jpg`;
}

// index.json thumbs are site-root-relative ("projects/<slug>/…"); frontmatter
// overrides may still be project-relative.
function projectThumb(p) {
  if (!p.thumb) return null;
  return p.thumb.startsWith('projects/') || p.thumb.startsWith('http')
    ? p.thumb
    : `projects/${p.id}/${p.thumb}`;
}

// tolerant subsequence match ("txcache" hits "texture cache")
function fuzzyMatch(needle, hay) {
  let i = 0;
  for (const ch of hay) {
    if (ch === needle[i]) i++;
    if (i === needle.length) return true;
  }
  return needle.length === 0;
}

function matchesFilters(entry) {
  for (const tag of state.activeTags) {
    if (!entry.tags.includes(tag)) return false;
  }
  if (!state.query) return true;
  const hay = `${entry.title} ${entry.desc} ${entry.client} ${entry.tags.join(' ')}`.toLowerCase();
  return state.query.split(/\s+/).every(tok => hay.includes(tok) || fuzzyMatch(tok, hay));
}

function tagCounts() {
  const counts = new Map();
  for (const e of gridEntries()) {
    for (const t of e.tags) counts.set(t, (counts.get(t) || 0) + 1);
  }
  return counts;
}

function renderGrid() {
  const grid = document.getElementById('work-grid');
  const entries = gridEntries().filter(matchesFilters);

  if (!entries.length) {
    grid.innerHTML = '<p class="grid-empty">no works match — clear filters or check back soon</p>';
    return;
  }

  grid.innerHTML = entries.map(e => {
    const external = e.kind === 'external';
    const tags = e.tags.map(t => `<span class="hashtag" data-tag="${esc(t)}">#${esc(t)}</span>`).join('');
    return `
      <a class="project-card${external ? ' is-external' : ''}"
         href="${esc(e.href)}"${external ? ' target="_blank" rel="noopener"' : ''}>
        <img class="project-thumb" src="${esc(e.thumb || '')}" alt="${esc(e.title)}" loading="lazy"
             onerror="this.outerHTML='<div class=&quot;project-thumb-placeholder&quot;>${esc(e.title)}</div>'">
        ${external ? `<span class="ext-badge">${esc(e.badge)}</span>` : ''}
        <div class="project-info">
          <h2 class="project-title">${esc(e.title)}</h2>
          <div class="project-meta">
            ${e.client ? `<span>${esc(e.client)}</span>` : ''}
            <span>${esc(e.date)}</span>
          </div>
          <p class="project-desc">${esc(e.desc)}</p>
          <div class="project-hashtags">${tags}</div>
        </div>
      </a>`;
  }).join('');

  grid.querySelectorAll('.hashtag').forEach(el => {
    el.addEventListener('click', ev => {
      ev.preventDefault();
      ev.stopPropagation();
      addTag(el.dataset.tag);
    });
  });

  applySidebarFilter();
}

// ---------- search box: free text + hashtag tokens ----------

function renderTokens() {
  const wrap = document.getElementById('search-tokens');
  wrap.innerHTML = [...state.activeTags].map(t => `
    <button class="token" data-tag="${esc(t)}" aria-label="Remove filter #${esc(t)}">
      #${esc(t)}<span class="token-x" aria-hidden="true">✕</span>
    </button>`).join('');
  wrap.querySelectorAll('.token').forEach(el => {
    el.addEventListener('click', () => {
      state.activeTags.delete(el.dataset.tag);
      renderTokens();
      renderGrid();
    });
  });
}

function addTag(tag) {
  if (!tag) return;
  state.activeTags.add(tag);
  const input = document.getElementById('search-input');
  input.value = '';
  state.query = '';
  renderTokens();
  renderGrid();
  input.focus();
}

function setupSearch() {
  const input = document.getElementById('search-input');
  const box = document.getElementById('search-box');
  const suggest = document.getElementById('search-suggest');
  let items = [];
  let sel = -1;

  const close = () => {
    suggest.hidden = true;
    input.setAttribute('aria-expanded', 'false');
    sel = -1;
  };

  const highlight = () => {
    suggest.querySelectorAll('li').forEach((li, i) => li.classList.toggle('is-sel', i === sel));
  };

  // Suggest hashtags matching the input. "#" alone lists everything.
  const open = () => {
    const raw = input.value.trim().toLowerCase();
    const tagMode = raw.startsWith('#');
    const q = tagMode ? raw.slice(1) : raw;
    if (!q && !tagMode) return close();
    const counts = tagCounts();
    items = [...counts.keys()]
      .filter(t => !state.activeTags.has(t))
      .map(t => {
        const lt = t.toLowerCase();
        const rank = !q ? 3 : lt.startsWith(q) ? 0 : lt.includes(q) ? 1 : fuzzyMatch(q, lt) ? 2 : -1;
        return { t, rank, n: counts.get(t) };
      })
      .filter(x => x.rank >= 0)
      .sort((a, b) => a.rank - b.rank || b.n - a.n || a.t.localeCompare(b.t))
      .slice(0, 8);
    if (!items.length) return close();
    sel = -1;
    suggest.innerHTML = items.map((x, i) => `
      <li role="option" data-tag="${esc(x.t)}" data-i="${i}">
        <span>#${esc(x.t)}</span><span class="suggest-count">${x.n}</span>
      </li>`).join('');
    suggest.hidden = false;
    input.setAttribute('aria-expanded', 'true');
  };

  box.addEventListener('click', () => input.focus());

  input.addEventListener('input', () => {
    const raw = input.value.trim().toLowerCase();
    // in "#tag" mode the text is a tag lookup, not a grid query
    state.query = raw.startsWith('#') ? '' : raw;
    open();
    renderGrid();
  });

  input.addEventListener('keydown', ev => {
    // legacy aliases (old WebKit/IE key names)
    const key = { Down: 'ArrowDown', Up: 'ArrowUp', Return: 'Enter', Esc: 'Escape' }[ev.key] || ev.key;
    if (key === 'ArrowDown' && !suggest.hidden) {
      ev.preventDefault();
      sel = (sel + 1) % items.length;
      highlight();
    } else if (key === 'ArrowUp' && !suggest.hidden) {
      ev.preventDefault();
      sel = (sel - 1 + items.length) % items.length;
      highlight();
    } else if (key === 'Enter') {
      if (sel >= 0) addTag(items[sel].t);
      else if (input.value.trim().startsWith('#') && items.length) addTag(items[0].t);
      close();
    } else if (key === 'Escape') {
      close();
    } else if (key === 'Backspace' && !input.value && state.activeTags.size) {
      const last = [...state.activeTags].pop();
      state.activeTags.delete(last);
      renderTokens();
      renderGrid();
    }
  });

  // mousedown beats the input's blur
  suggest.addEventListener('mousedown', ev => {
    const li = ev.target.closest('li[data-tag]');
    if (li) {
      ev.preventDefault();
      addTag(li.dataset.tag);
      close();
    }
  });

  document.addEventListener('click', ev => {
    if (!box.contains(ev.target)) close();
  });
}

// ---------- sidebar ----------

function renderSidebar() {
  const builtSlugs = new Set(state.projects.map(p => p.id));

  // header links are the static icon-nav in index.html; the sidebar row
  // carries the rest (cv / github / vimeo)
  const contact = document.getElementById('cv-contact');
  const sidebarLinks = (state.cv.links || []).filter(l => l.placement !== 'header');
  if (contact && sidebarLinks.length) {
    contact.innerHTML = sidebarLinks.map(l => {
      const external = /^https?:/.test(l.url);
      return `<a href="${esc(l.url)}"${external ? ' target="_blank" rel="noopener"' : ''}>${esc(l.label)}</a>`;
    }).join('');
  }

  const list = document.getElementById('cv-list');

  list.innerHTML = state.cv.sections.map(section => {
    const items = section.items.map(item => {
      const built = builtSlugs.has(item.slug);
      const slug = ` data-slug="${esc(item.slug)}"`;
      if (built) {
        return `
          <a class="cv-item"${slug} href="projects/${esc(item.slug)}/">
            <span class="cv-item-year">${item.year}</span>
            <span class="cv-item-title">${esc(item.title)}</span>
          </a>`;
      }
      if (item.link) {
        return `
          <a class="cv-item"${slug} href="${esc(item.link)}" target="_blank" rel="noopener">
            <span class="cv-item-year">${item.year}</span>
            <span class="cv-item-title">${esc(item.title)}</span>
            <span class="cv-item-ext">↗</span>
          </a>`;
      }
      return `
        <div class="cv-item is-inert"${slug}>
          <span class="cv-item-year">${item.year}</span>
          <span class="cv-item-title">${esc(item.title)}</span>
        </div>`;
    }).join('');
    return `
      <section class="cv-section">
        <h2 class="cv-section-title" role="button" tabindex="0" aria-expanded="true">
          <span>${esc(section.title)}</span><span class="cv-section-caret" aria-hidden="true">▾</span>
        </h2>
        <div class="cv-section-items">${items}</div>
      </section>`;
  }).join('') + `
    <div class="cv-tail">
      <strong>STACK</strong>
      <p>${state.cv.stack.map(esc).join(' · ')}</p>
      <strong>SKILLS</strong>
      <p>${state.cv.skills.map(esc).join(' · ')}</p>
    </div>`;

  list.querySelectorAll('.cv-section-title').forEach(head => {
    const toggle = () => {
      const section = head.closest('.cv-section');
      const collapsed = section.classList.toggle('is-collapsed');
      head.setAttribute('aria-expanded', String(!collapsed));
    };
    head.addEventListener('click', toggle);
    head.addEventListener('keydown', ev => {
      if (ev.key === 'Enter' || ev.key === ' ') { ev.preventDefault(); toggle(); }
    });
  });
}

// Dim sidebar entries that don't match the active search/tag filters; fade
// whole sections when nothing inside them matches. CV document order is
// preserved — this highlights rather than reflows.
function applySidebarFilter() {
  const list = document.getElementById('cv-list');
  if (!list || !state.cv) return;
  const filtering = state.query || state.activeTags.size;
  const bySlug = new Map(cvItems().map(i => [i.slug, i]));

  list.querySelectorAll('.cv-item[data-slug]').forEach(el => {
    if (!filtering) { el.classList.remove('is-dim'); return; }
    const item = bySlug.get(el.dataset.slug);
    const tags = item?.tags || [];
    let ok = [...state.activeTags].every(t => tags.includes(t));
    if (ok && state.query) {
      const hay = `${item.title} ${item.blurb || ''} ${item.year} ${tags.join(' ')}`.toLowerCase();
      ok = state.query.split(/\s+/).every(tok => hay.includes(tok) || fuzzyMatch(tok, hay));
    }
    el.classList.toggle('is-dim', !ok);
  });

  list.querySelectorAll('.cv-section').forEach(section => {
    const items = section.querySelectorAll('.cv-item[data-slug]');
    const anyLit = !filtering || [...items].some(el => !el.classList.contains('is-dim'));
    section.classList.toggle('is-dim', !anyLit);
  });
}

function setupSidebarToggle() {
  const btn = document.getElementById('sidebar-toggle');
  const apply = collapsed => {
    document.body.classList.toggle('sidebar-collapsed', collapsed);
    btn.setAttribute('aria-expanded', String(!collapsed));
  };
  // collapsed by default on mobile, otherwise honor the last explicit choice;
  // until the user chooses, follow viewport changes (the initial window size
  // can be transient during load)
  const mq = window.matchMedia('(max-width: 768px)');
  const savedChoice = () => {
    try { return localStorage.getItem('drmbt-sidebar'); } catch { return null; }
  };
  const saved = savedChoice();
  apply(saved ? saved === 'collapsed' : mq.matches);
  mq.addEventListener('change', e => {
    if (!savedChoice()) apply(e.matches);
  });
  btn.addEventListener('click', () => {
    const next = !document.body.classList.contains('sidebar-collapsed');
    apply(next);
    try { localStorage.setItem('drmbt-sidebar', next ? 'collapsed' : 'open'); } catch {}
  });
}

// ---------- util / boot ----------

function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

async function init() {
  [state.cv, state.projects] = await Promise.all([
    fetchJson('data/cv.json', { sections: [], stack: [], skills: [] }),
    fetchJson('projects/index.json', []),
  ]);

  renderSidebar();
  renderGrid();
  renderTokens();
  setupSidebarToggle();
  setupSearch();

  // keep the sticky filter bar pinned right under the header at any width
  const header = document.querySelector('.site-header');
  const setHeaderH = () =>
    document.documentElement.style.setProperty('--header-h', `${header.offsetHeight}px`);
  setHeaderH();
  window.addEventListener('resize', setHeaderH);
}

init();
